import { useLocalSearchParams, useRouter } from "expo-router";
import { Pressable, ScrollView, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";

const content: Record<string, { eyebrow: string; title: string; intro: string; cards: { title: string; body: string }[] }> = {
  corporate: { eyebrow: "LIONX BUSINESS", title: "حلول للشركات", intro: "مسار B2B لمتطلبات النمو والتسويق والتحول الرقمي مع عرض نطاق ومراجعة قبل التنفيذ.", cards: [{ title: "Quote Builder", body: "اختر الخدمات المطلوبة وأرسل طلب نطاق مبدئي للفريق." }, { title: "مراجعة يدوية", body: "أي شروط ائتمانية أو أسعار مخصصة تحتاج مراجعة واعتمادًا منفصلًا." }] },
  about: { eyebrow: "ABOUT LIONX", title: "عن LIONX", intro: "مول رقمي يجمع الخدمات والاشتراكات والأدوات ومسارات النمو في تجربة عربية واضحة.", cards: [{ title: "الوضوح أولًا", body: "نوضح ما هو متاح وما يحتاج مراجعة قبل تنفيذ الطلب." }, { title: "منصة واحدة", body: "تجربة مشتركة للجوال والويب، مع كتالوج منظم ومسارات B2C وB2B." }] },
  faq: { eyebrow: "HELP CENTER", title: "الأسئلة الشائعة", intro: "إجابات أولية تساعدك على فهم الطلب والدفع والتتبع.", cards: [{ title: "متى يتم تنفيذ الطلب؟", body: "بعد مراجعة البيانات وتأكيد طريقة الدفع، تظهر حالة الطلب في التتبع." }, { title: "هل الدفع إلكتروني فوري؟", body: "النسخة الحالية تسجل الطلب للمراجعة اليدوية ولا تدعي تحصيلًا آليًا." }] },
  contact: { eyebrow: "CONTACT", title: "تواصل معنا", intro: "أرسل تفاصيل طلبك أو استفسارك من خلال القنوات الرسمية بعد اعتمادها.", cards: [{ title: "الدعم", body: "احتفظ برقم الطلب عند التواصل حتى نتمكن من مراجعة الحالة." }, { title: "طلبات الشركات", body: "استخدم Quote Builder لإرسال نطاق مبدئي واضح." }] },
  terms: { eyebrow: "LEGAL", title: "الشروط والأحكام", intro: "هذه واجهة أولية للنص القانوني، وتحتاج مراجعة قانونية واعتمادًا قبل الإنتاج.", cards: [{ title: "الطلبات", body: "يخضع تنفيذ الخدمة لتوفرها ومراجعة البيانات وطريقة الدفع." }, { title: "الأسعار", body: "الأسعار الظاهرة للاختبار ولا تعتبر عرضًا نهائيًا قبل التأكيد." }] },
  privacy: { eyebrow: "PRIVACY", title: "الخصوصية", intro: "نوضح هنا مبادئ التعامل مع بيانات المستخدم، ويجب اعتماد النص النهائي قبل الإطلاق.", cards: [{ title: "الحد الأدنى من البيانات", body: "نجمع ما يلزم لمعالجة الطلب والدعم فقط." }, { title: "عدم مشاركة حساسة", body: "لا ترسل كلمات مرور أو مفاتيح API أو بيانات دفع حساسة داخل المحادثة." }] },
  vip: { eyebrow: "LIONX VIP", title: "عضوية VIP", intro: "مزايا خاصة وخدمات كونسيرج، مع عروض وأسعار تعتمد بعد اعتماد المورد والنطاق.", cards: [{ title: "VIP Privé", body: "مسار للخدمات الخاصة والسفر والإقامات والطلبات المخصصة." }, { title: "حالة العرض", body: "لا تظهر عضوية مدفوعة أو سعر نهائي قبل تأكيد التفاصيل." }] },
  blog: { eyebrow: "LIONX JOURNAL", title: "المدونة", intro: "محتوى تعليمي عن الأدوات الرقمية والنمو والتسويق، جاهز للتوسعة بمقالات موثقة.", cards: [{ title: "دليل البدء", body: "تعلم اختيار الخدمة المناسبة قبل إرسال الطلب." }, { title: "ملاحظات السوق", body: "محتوى تحليلي يحتاج مصادر واعتمادًا قبل النشر العام." }] },
  offers: { eyebrow: "OFFERS", title: "العروض", intro: "مساحة للعروض المعتمدة فقط؛ لا نعرض خصومات أو أرقامًا غير موثقة.", cards: [{ title: "عروض قادمة", body: "ستظهر هنا العروض بعد اعتماد المورد والشروط وتاريخ الانتهاء." }] },
  academy: { eyebrow: "ACADEMY", title: "أكاديمية LIONX", intro: "دروس قصيرة لبناء حضور رقمي وفهم الأدوات والخدمات المتاحة.", cards: [{ title: "المسار الأساسي", body: "ابدأ بتحديد الهدف والجمهور قبل اختيار أدوات التسويق." }, { title: "المسار التجاري", body: "للشركات التي تحتاج نطاقًا وعرض سعر قابلًا للمراجعة." }] },
  tools: { eyebrow: "TOOLS", title: "أدوات رقمية", intro: "أدوات مساعدة للبحث والتخطيط والاختيار داخل منظومة LIONX.", cards: [{ title: "مقارنة الخدمات", body: "قارن الوصف والتسليم والسعر الظاهر قبل الإضافة للسلة." }, { title: "حاسبة النطاق", body: "تستخدم لاحقًا لتجميع الخدمات في طلب B2B." }] },
  affiliate: { eyebrow: "AFFILIATE", title: "برنامج الشركاء", intro: "مسار أولي للشركاء الذين يرشحون خدمات LIONX، ويحتاج شروطًا وعمولات معتمدة قبل التفعيل.", cards: [{ title: "كيف يعمل؟", body: "تشارك رابطًا أو توصية، ثم تتم مراجعة الإحالات قبل احتساب أي عمولة." }, { title: "الحالة الحالية", body: "البرنامج تعريفي في هذه النسخة ولا ينشئ التزامًا ماليًا تلقائيًا." }] },
  wishlist: { eyebrow: "WISHLIST", title: "المفضلة", intro: "احفظ الخدمات التي تريد مراجعتها لاحقًا. التخزين السحابي يحتاج حسابًا ومزامنة في مرحلة لاحقة.", cards: [{ title: "قائمة محلية", body: "يمكن توسيعها لاحقًا باستخدام AsyncStorage أو حساب LIONX." }] },
};

export default function ContentScreen() {
  const { slug } = useLocalSearchParams<{ slug: string }>();
  const router = useRouter();
  const page = content[slug] ?? content.about;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-4 pt-3"><ScrollView contentContainerStyle={{ paddingBottom: 32 }}><Pressable onPress={() => router.back()} style={({ pressed }) => [{ opacity: pressed ? 0.6 : 1 }]}><Text className="text-sm font-bold text-primary">رجوع</Text></Pressable><View className="mt-5 rounded-3xl border border-primary bg-surface p-5"><Text className="text-xs font-bold tracking-widest text-primary">{page.eyebrow}</Text><Text className="mt-2 text-3xl font-black text-foreground">{page.title}</Text><Text className="mt-3 text-sm leading-6 text-muted">{page.intro}</Text></View><View className="mt-5 gap-3">{page.cards.map((card) => <View key={card.title} className="rounded-2xl border border-border bg-surface p-4"><Text className="text-base font-black text-foreground">{card.title}</Text><Text className="mt-2 text-sm leading-6 text-muted">{card.body}</Text></View>)}</View></ScrollView></ScreenContainer>;
}
